# Generated by Django 2.2.14 on 2020-07-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_testnbvnbvnv"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testhghg",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hgfhgfh", models.BigIntegerField()),
            ],
        ),
    ]
