# Generated by Django 2.2.14 on 2020-07-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_testhghg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testsdfhws',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('efgtqaera', models.BigIntegerField()),
            ],
        ),
    ]
